backend-tests:
	@echo "Running backend unit test suite"

frontend-tests:
	@echo "Running frontend unit test suite"

build:
	@echo "Running build"

deploy:
	@echo "Deploying..."

integration-tests:
	@echo "Running integration test suite"
