jobs:
- name: test-app-1
  plan:
  - get: app1
    trigger: true
  - task: backend-unit-tests
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: golang
      inputs:
      - name: app1
      run:
        path: sh
        args:
        - -c
        - cd app1/src/app1 && make backend-tests
  - task: frontend-unit-tests
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: golang
      inputs:
      - name: app1
      run:
        path: sh
        args:
        - -c
        - cd app1/src/app1 && make frontend-tests

- name: build-app-1
  plan:
  - get: app1
    trigger: true
    passed:
    - test-app-1
  - task: build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: golang
      inputs:
      - name: app1
      run:
        path: sh
        args:
        - -c
        - cd app1/src/app1 && make build

- name: deploy-app-1
  plan:
  - get: app1
    trigger: true
    passed:
    - build-app-1
  - task: build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: golang
      inputs:
      - name: app1
      run:
        path: sh
        args:
        - -c
        - cd app1/src/app1 && make deploy

- name: test-app-2
  plan:
  - get: app2
    trigger: true
  - task: backend-unit-tests
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: golang
      inputs:
      - name: app2
      run:
        path: sh
        args:
        - -c
        - cd app2/src/app2 && make backend-tests
  - task: frontend-unit-tests
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: golang
      inputs:
      - name: app2
      run:
        path: sh
        args:
        - -c
        - cd app2/src/app2 && make frontend-tests

- name: build-app-2
  plan:
  - get: app2
    trigger: true
    passed:
    - test-app-2
  - task: build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: golang
      inputs:
      - name: app2
      run:
        path: sh
        args:
        - -c
        - cd app2/src/app2 && make build

- name: deploy-app-2
  plan:
  - get: app2
    trigger: true
    passed:
    - build-app-2
  - task: build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: golang
      inputs:
      - name: app2
      run:
        path: sh
        args:
        - -c
        - cd app2/src/app2 && make deploy


resources:
- name: app1
  type: git
  source:
    uri: "https://github.com/factorypreset/bad-concourse"
    branch: main
    paths:
      - src/app1

- name: app2
  type: git
  source:
    uri: "https://github.com/factorypreset/bad-concourse"
    branch: main
    paths:
      - src/app2


